      DOUBLE PRECISION DEPSILON
      PARAMETER (DEPSILON = 2.0d0**( - 36))
      DOUBLE PRECISION SEPSILON
      PARAMETER (SEPSILON = 2.0d0**( - 14))

      INTEGER IINFTY
      PARAMETER (IINFTY = 2**30)

