FIND_LIBRARY(COIN_CLP_LIBRARY
  NAMES Clp libClp
  HINTS ${COIN_ROOT_DIR}/lib/coin
  HINTS ${COIN_ROOT_DIR}/lib
)

#FIND_LIBRARY(TURBOACTIVATE_LIBRARY
#  NAMES TurboActivate libTurboActivate
#  HINTS /usr/local/lib
#)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CLP DEFAULT_MSG
  COIN_CLP_LIBRARY
)

SET(COIN_CLP_LIBRARIES "${COIN_CLP_LIBRARY}")



